name: Repo Health

on:
  pull_request:
    branches: [dev, master, main]
  workflow_dispatch:

jobs:
  repo_health:
    uses: OpenVoiceOS/gh-automations/.github/workflows/repo-health.yml@fa39846b074ac7a856c8af5f8c0dec12b1fff1aa
    secrets: inherit
    with:
      version_file: 'ovos_option_matcher_fuzzy/version.py'
